# Generated by Django 3.2.8 on 2021-10-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Java', '0002_alter_adddata_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddata',
            name='Type',
            field=models.TextField(max_length=20),
        ),
    ]
