# Generated by Django 3.2.8 on 2021-10-31 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Java', '0004_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='Image',
        ),
    ]
