# Generated by Django 3.2.8 on 2021-10-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Java', '0005_remove_notes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='Image',
            field=models.ImageField(null=True, upload_to='img/%y'),
        ),
    ]
