# Generated by Django 3.2.8 on 2021-10-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Java', '0006_notes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='Notes',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
    ]
