# Generated by Django 3.2.8 on 2021-11-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Java', '0010_alter_notes_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='Notes',
            new_name='Doubts',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='Image',
            new_name='Solution',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='Topic',
        ),
    ]
