# Generated by Django 3.2.8 on 2021-11-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Java', '0011_auto_20211101_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='Solution',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
