# Generated by Django 3.2.8 on 2021-11-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Java', '0012_alter_notes_solution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Doubts',
        ),
    ]
