# Generated by Django 3.2.8 on 2021-11-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Java', '0014_auto_20211105_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddata',
            name='Solution',
            field=models.URLField(max_length=10000),
        ),
    ]
